spring:
  datasource:
    url: jdbc:mysql://localhost:3306/welcome?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: a13232613.
    driver-class-name: com.mysql.cj.jdbc.Driver